### DISCUSSION TITLE
Home-assistant configuration for multiple zones

### DISCUSSION THREAD

**Discussion by saikek** [rand256/valetudo#390] [Q&A] [answered]
Hi, I'm not able to find this info anywhere:
1) Where do you get name of `zone` ? (is it some strange UID or it is equals to the name of zone in ValetudoRe ui ? 
2) How can I specify multiple zones for cleanup in script:
```
clean_multiple_zones:
  alias: "Clean multople zones"
  sequence:
    - service: vacuum.send_command
      data:
        entity_id: vacuum.vacuum1
        command: zoned_cleanup
        params:
          'zone_ids': ['zone1', 'zone2']
```

Would this be enough ?

**Comment by pidator** [comment, marked as answer]
Have you already take a look at [this](https://github.com/rand256/valetudo/wiki/MQTT-API#Topic_valetudorockrobodestinations) or [this](https://github.com/rand256/valetudo/wiki/MQTT-API#Topic_valetudorockrobocustom_command)?

**Reply by saikek** [reply]
This seems to work, if zones are properly defined:
```
script:
 vacuum_kitchen_dining_hallway_bathroom:
       alias: "vacuum all but rooms"
       sequence:
         - service: vacuum.send_command
           data:
             entity_id: vacuum.valetudo
             command: zoned_cleanup
             params:
                 zone_ids:
                  - Kitchen
                  - Dining
                  - Hallway
                  - Bathroom
```
