### ISSUE TITLE
[Question] Map size different to Valetudo-Mapper Hassio-Addon and "normal" Docker

### ISSUE THREAD

**Issue by thundergreen** [rand256/valetudo#466]
**Describe the bug**

When i install Valetudo Mapper via docker (not Hassio-Addon) my Map is small than the Hassio addon
**How to Reproduce**

1. start docker container with config file (I use docker-compose.yaml)
2. camera is added to Home-Assistant but smaller
3. Both site codes (Lovelace) are identical!

**Expected behavior**

Both camera Images should be the same size

**Screenshots**

With Valetudo Mapper Hassio-Addon:

![image](https://user-images.githubusercontent.com/13320319/132959573-31deaeef-c2b2-4c7c-920f-ed876d90785b.png)

With Valetudo-Mapper "normal" Docker run

![image](https://user-images.githubusercontent.com/13320319/132959596-d6530fbb-9404-4034-a7c6-d733a828f7f0.png)

**Vacuum Model:** 
Gen1
**Valetudo Version:** 
latest Docker Image
**User-Agent** 

**Additional context**

My config file:

```
{
  "mqtt": {
    "identifier": "upstairs",
    "topicPrefix": "valetudo",
    "autoconfPrefix": "homeassistant",
    "broker_url": "mqtt://hass:hass@192.168.1.41:1883",
    "caPath": "",
    "mapDataTopic": "valetudo/upstairs/map_data",
    "minMillisecondsBetweenMapUpdates": 10000,
    "publishMapImage": true,
    "publishMapData": true
  },
  "mapSettings": {
    "colors": {
      "background": "#33a1f5",
      "background2": "#046cd4",
      "floor": "#56affc",
      "obstacle_strong": "#a1dbff",
      "path": "white",
      "forbidden_marker": "red",
      "forbidden_zone": "rgba(255, 0, 0, 0.38)",
      "cleaned_marker": "rgba(53, 125, 46, 1.0)",
      "cleaned_zone": "rgba(107, 244, 66, 0.3)",
      "cleaned_block": "rgba(107, 244, 36, 0.34)"
    },
    "drawPath": true,
    "drawCharger": true,
    "drawRobot": true,
    "drawCurrentlyCleanedZones": true,
    "drawCurrentlyCleanedBlocks": true,
    "drawForbiddenZones": true,
    "drawVirtualWalls": true,
    "scale": 4,
    "gradientBackground": false,
    "autoCrop": 20
  },
  "webserver": {
    "enabled": true,
    "port": 3000
  }

```

My Docker-compose.yaml:

```
---
version: "2.1"
services:
  valetudo-mapper:
    image: rand256/valetudo-mapper
    container_name: valetudo-mapper
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /media/hassio/Storage/Docker/Valetudo-Mapper/config.json:/app/config.json
    ports:
      - 4050:3000
    restart: unless-stopped
```
