### ISSUE TITLE
custom_command, segment_ids. What is wrong?

### ISSUE THREAD

**Issue by labaland** [rand256/valetudo#504]
Hi! Sry bad english :P 
I did not find any answer on my question after a lot of google searches.

I want to be able to start a cleaning for multible rooms at once from HA and i followed this guide:
https://valetudo.cloud/pages/integrations/home-assistant-integration.html

So after following that guide i can get the rooms id's i want to clean like this: ["17","19","21"]
```
        variables:
          segments: '{{expand("group.vacuum_rooms") | selectattr("state","eq","on")
          | map(attribute="attributes.room_id") | list | to_json}}'
```
The problem is i cant start the cleaning with this service:
```
    - service: mqtt.publish
      data:
        topic: valetudo/slaven/custom_command
        payload_template: '{"segment_ids": {{segments}}}'
```

But if i change  ["17","19","21"]  to  [17, 19 , 21]   it works.. 

I get this in the log on my vacuum:
"2023-07-16T06:25:32.955Z MQTT Error : segmented_cleanup : Invalid segment_ids"

How do you guys doing this?
